### ISSUE TITLE
#237 causes over-class "flickering" when drop target has child elements (Chrome)

### ISSUE THREAD

**Issue by darynmitchell** [nervgh/angular-file-upload#332]
Anyone else find that #237 has introduced flickering when moving around inside the drag target?

I make the drop target background color different when dragging, and I'm seeing lots of flicker introduced.

My drop target is not just a div with simple text: Inside the drop target I've got an image, and a couple of styled divs of text. As far as I can tell, whenever dragging from the drop target background to now be over one of the child elements, the dragleave event is fired with event.currentTarget === the drop target, causing the over-class to be removed. The over-class is then immediately added back, resulting in flicker.

This did not happen in 1.1.1 when onDragLeave used to compare event.target instead of event.currentTarget.

Enviroment:
angular-file-upload 1.1.5
Windows 7, using Chrome v39 (FF + IE11 seem okay)

**Comment by EccoTheDolphin** [comment]
Could you provide an example to reproduce?

**Comment by sergey-safonov** [comment]
Have the same issue, simplest workaround: http://stackoverflow.com/questions/10867506/dragleave-of-parent-element-fires-when-dragging-over-children-elements

**Comment by desertlion** [comment]
Just stumble upon this issue on my chrome App, my friend found a fix for it, but I cant edit the core file because when I bower update the fix will go also. So, I override it through my controller. 
```
FileUploader.FileDrop.prototype.onDragLeave = function(event) {
			if (event.originalEvent.pageX !== 0 || event.originalEvent.pageY !== 0) return false; // the fix
			if (event.currentTarget !== this.element[0]) return;
			this._preventAndStop(event);
			angular.forEach(this.uploader._directives.over, this._removeOverClass, this);
		};
```
In the core file it is on angular-file-upload.js line 1168.

**Comment by nervgh** [comment]
fixed https://github.com/nervgh/angular-file-upload/pull/286

**Comment by Dzivo** [comment]
Sorry guys but it think this is still happening in  Version 85.0.4183.102 (Official Build) (64-bit)

I can make a video. Also it works in firefox

**Comment by lmarkscp** [comment]
This is happening again in Version 101.0.4951.54 (Official Build) (x86_64).  It does not happen in Firefox.
